sudo: required
dist: xenial
language: python
python:
  -  "3.7"

services:
  - docker

script: true

after_success:
  - bash <(curl -s https://raw.githubusercontent.com/sesam-community/guidelines/master/after_success.sh)
